git clone https://github.com/TheAlgorithms/Java.git SourceFiles/Java
git clone https://github.com/TheAlgorithms/Python.git SourceFiles/Python
git clone https://github.com/TheAlgorithms/C-Sharp.git SourceFiles/C-Sharp
git clone https://github.com/TheAlgorithms/Ruby.git SourceFiles/Ruby
git clone https://github.com/TheAlgorithms/Javascript.git SourceFiles/Javascript
git clone https://github.com/TheAlgorithms/C.git SourceFiles/C
git clone https://github.com/TheAlgorithms/Go.git SourceFiles/Go
git clone https://github.com/TheAlgorithms/C-Plus-Plus.git SourceFiles/C-Plus-Plus
git clone https://github.com/TheAlgorithms/Scala.git SourceFiles/Scala
git clone https://github.com/TheAlgorithms/MATLAB-Octave.git SourceFiles/MATLAB-Octave
