git clone https://github.com/TheAlgorithms/Java.git SourceFiles/Java
git clone https://github.com/TheAlgorithms/Python.git SourceFiles/Python
git clone https://github.com/TheAlgorithms/C-Sharp.git SourceFiles/C-Sharp
git clone https://github.com/GavinYellow/SharpSCADA.git SourceFiles/C-Sharp/One
git clone https://github.com/ruby/ruby.git SourceFiles/Ruby
git clone https://github.com/airbnb/ruby.git SourceFiles/Ruby/airbnb
git clone https://github.com/TheAlgorithms/Javascript.git SourceFiles/Javascript
git clone https://github.com/airbnb/javascript.git SourceFiles/Javascript/one
git clone https://github.com/pubnub/javascript.git SourceFiles/Javascript/two
git clone https://github.com/TheAlgorithms/C.git SourceFiles/C
git clone https://github.com/justin-lathrop/c.git SourceFiles/C/one
git clone https://github.com/andrewchambers/c.git SourceFiles/C/two
git clone https://github.com/TheAlgorithms/Go.git SourceFiles/Go
git clone https://github.com/golang/go.git SourceFiles/Go/One
git clone https://github.com/TheAlgorithms/C-Plus-Plus.git SourceFiles/C-Plus-Plus
git clone https://github.com/TheAlgorithms/Scala.git SourceFiles/Scala
git clone https://github.com/scalaz/scalaz.git SourceFiles/Scala/One
git clone https://github.com/aludnam/MATLAB.git SourceFiles/MATLAB
git clone https://github.com/dmpe/R.git SourceFiles/R
git clone https://github.com/datadolphyn/R.git SourceFiles/R/one
git clone https://github.com/twbs/bootstrap.git SourceFiles/CSS
git clone https://github.com/dompdf/dompdf.git SourceFiles/PHP
git clone https://github.com/PHPMailer/PHPMailer.git SourceFiles/PHP/one
git clone https://github.com/kraih/mojo.git SourceFiles/Perl
git clone https://github.com/sadsfae/misc-scripts.git SourceFiles/Shell
git clone https://github.com/oscm/shell.git SourceFiles/Shell/one
